// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRecordingStatus():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ProcessVoiceCommand(arg1:string):Promise<string>;

export function StartRecording():Promise<string>;

export function StopRecording():Promise<string>;
