// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRecordingStatus() {
  return window['go']['main']['App']['GetRecordingStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ProcessVoiceCommand(arg1) {
  return window['go']['main']['App']['ProcessVoiceCommand'](arg1);
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}
