// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableTools() {
  return window['go']['main']['App']['GetAvailableTools']();
}

export function GetConversationHistory() {
  return window['go']['main']['App']['GetConversationHistory']();
}

export function GetToolDescription(arg1) {
  return window['go']['main']['App']['GetToolDescription'](arg1);
}

export function IsRecording() {
  return window['go']['main']['App']['IsRecording']();
}

export function ProcessVoiceCommand(arg1) {
  return window['go']['main']['App']['ProcessVoiceCommand'](arg1);
}

export function ProcessVoiceCommandAuto() {
  return window['go']['main']['App']['ProcessVoiceCommandAuto']();
}

export function RecordAndTranscribe() {
  return window['go']['main']['App']['RecordAndTranscribe']();
}

export function RecordAndTranscribeWithLanguage(arg1) {
  return window['go']['main']['App']['RecordAndTranscribeWithLanguage'](arg1);
}

export function ResetConversation() {
  return window['go']['main']['App']['ResetConversation']();
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}
