// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {llms} from '../models';

export function GetAvailableTools():Promise<Array<string>>;

export function GetConversationHistory():Promise<Array<llms.Message>>;

export function GetToolDescription(arg1:string):Promise<string>;

export function IsRecording():Promise<boolean>;

export function ProcessVoiceCommand(arg1:string):Promise<string>;

export function ProcessVoiceCommandAuto():Promise<string>;

export function RecordAndTranscribe():Promise<string>;

export function RecordAndTranscribeWithLanguage(arg1:string):Promise<string>;

export function ResetConversation():Promise<void>;

export function SetAPIKey(arg1:string):Promise<void>;
